### ISSUE TITLE
BrowserStackTunnel.jar needs to be updated

### ISSUE THREAD

**Issue by apaatsio** [dbrans/browserstack-cli#12]
Running `browserstack tunnel` gives the following error:

```
There is a new version of BrowserStackTunnel.jar available on server. Please upd
ate from :

http://www.browserstack.com/BrowserStackTunnel.jar
```

**Comment by justspamjustin** [comment]
I would like to second this.  I have a problem that works with the new jar, but not the old.

**Comment by jfromaniello** [comment]
where is this stored?

**Comment by Strajk** [comment]
Same issue, when I run
`browserstack tunnel localhost:9000` I got `Invalid or corrupt jarfile ~/.browserstack/BrowserStackTunnel.jar` error

After replacing the file with one downloaded from http://www.browserstack.com/BrowserStackTunnel.jar
 everything works

**Comment by jfromaniello** [comment]
Browseroverflow downloads this:

https://github.com/airportyh/browseroverflow/blob/master/lib/get_browserstack_jar.js

**Comment by airportyh** [comment]
I don't think it tries to re-download the jar once it's there, I assume that is the problem. The behavior of the jar itself has changed over time. At one point it would autoupdate itself. Probably a manual process would be more reliable, something like `browserstack tunnel-update-jar`.

**Comment by apaatsio** [comment]
Closing as stale.
